# -*- coding: utf-8 -*-

from . import models
from . import hr_department
from . import requisitions
from . import segments
from . import age
from . import job_tab
from . import contract_type
from . import hr_job
from . import trial_period
from . import jornada
from . import activities
from . import activities_knowledge
from . import tools_knowledge
from . import schooling
from . import language
from . import language_level
from . import competencies
from . import internal_relations
from . import external_relations
from . import performance_standars
from . import branchType
from . import businessType
from . import legalRepresentative
from . import stampCertificate
from . import imssRegistration
from . import hr_job
from . import res_company
from . import jobAppAttachment
from . import clinic
from . import multiples_files
from . import vigency_complement
from . import hr_applicant
from . import hr_applicant_doc
from . import mail_mail
from . import hr_employee
from . import credentials
from . import hr_contract
from . import contract_format
from . import type_format
from . import applicant_refuse_reason
